<?php

$myTask = [
    [
        'id' => 1,
        'title' => 'Tugas 2 PHP',
        'subtitle' => 'Form Data Pegawai',
        'd-title' => 'Tugas 2 PhP | Form Data Pegawai',
        'img' => 'assets/img/portfolio/tugas2php1.png',
        'img-2' => 'assets/img/portfolio/tugas2php2.png',
        'img-3' => 'assets/img/portfolio/tugas2php3.png',
        'a-img' => 'assets/img/portfolio/tugas2php1.png',
        'div' => 'filter-php',
        'category' => 'Pemrograman PHP',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '28 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-php/tree/tugas2-php',
        'portofolio-title' => 'Form Data Pegawai',
        'portofolio-desc' => 'Ini adalah Tugas 2 PHP, membuat sebuah form dengan method POST dengan form builder bootstrap dari startbootstrap. Tampilkan populasi data di atas jika sudah diklik tombol simpan, dengan tambahan data: (menggunakan tabel dan untuk data angka gunakan fungsi number_format php) untuk yang bisa menggunkan modal bootstrap dipersilahkan'
    ],
    [
        'id' => 2,
        'title' => 'Tugas 3 PHP',
        'subtitle' => 'Daftar Mahasiswa',
        'd-title' => 'Tugas 3 PhP | Daftar Mahasiswa',
        'img' => 'assets/img/portfolio/tugas3php1.png',
        'img-2' => 'assets/img/portfolio/tugas3php2.png',
        'img-3' => 'assets/img/portfolio/tugas3php3.png',
        'a-img' => 'assets/img/portfolio/tugas3php1.png',
        'div' => 'filter-php',
        'category' => 'Pemrograman PHP',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '30 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-php/tree/tugas3-php',
        'portofolio-title' => 'Daftar Mahasiswa',
        'portofolio-desc' => 'Ini adalah Tugas 3 PHP, membuat daftar nilai mahasiswa dengan array associative serta array scalar'
    ],
    [
        'id' => 3,
        'title' => 'Tugas 4 PHP',
        'subtitle' => 'Daftar Gaji Pegawai',
        'd-title' => 'Tugas 4 PhP | Daftar Gaji Pegawai',
        'img' => 'assets/img/portfolio/tugas4php1.png',
        'img-2' => 'assets/img/portfolio/tugas4php2.png',
        'img-3' => 'assets/img/portfolio/tugas4php3.png',
        'a-img' => 'assets/img/portfolio/tugas4php1.png',
        'div' => 'filter-php',
        'category' => 'Pemrograman PHP',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '2 October 2022',
        'project-url' => 'https://github.com/andik71/msib3-php/tree/tugas4-php',
        'portofolio-title' => 'Daftar Gaji Pegawai',
        'portofolio-desc' => 'Ini adalah Tugas 4 PHP, membuat Class Pegawai dengan Constructor dengan operator pada pertemuan sebelumnya'
    ],
    [
        'id' => 4,
        'title' => 'Tugas 5 PHP',
        'subtitle' => 'Tabel Bangun 2 Dimensi',
        'd-title' => 'Tugas 5 PhP | Tabel Bangun 2 Dimensi',
        'img' => 'assets/img/portfolio/tugas5php1.png',
        'img-2' => 'assets/img/portfolio/tugas5php2.png',
        'img-3' => 'assets/img/portfolio/tugas5php3.png',
        'a-img' => 'assets/img/portfolio/tugas5php1.png',
        'div' => 'filter-php',
        'category' => 'Pemrograman PHP',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '3 October 2022',
        'project-url' => 'https://github.com/andik71/msib3-php/tree/tugas5-php',
        'portofolio-title' => 'Tabel Bangun 2 Dimensi',
        'portofolio-desc' => 'Ini adalah Tugas 5 PHP, membuat abstract class Bangun 2D'
    ],
    [
        'id' => 5,
        'title' => 'Tugas 1 Javascript',
        'subtitle' => 'Tabel Data Gaji',
        'd-title' => 'Tugas 1 Javascript | Tabel Data Gaji',
        'img' => 'assets/img/portfolio/tugas1js1.png',
        'img-2' => 'assets/img/portfolio/tugas1js2.png',
        'img-3' => 'assets/img/portfolio/tugas1js3.png',
        'a-img' => 'assets/img/portfolio/tugas1js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Tabel Data Gaji',
        'portofolio-desc' => 'Ini adalah Tugas 1 Javascript, membuat dokumen html dengan menampilkan value menggunakan document write javascript'
    ],
    [
        'id' => 6,
        'title' => 'Tugas 2 Javascript',
        'subtitle' => 'Daftar Pegawai',
        'd-title' => 'Tugas 2 Javascript | Daftar Pegawai',
        'img' => 'assets/img/portfolio/tugas2js1.png',
        'img-2' => 'assets/img/portfolio/tugas2js2.png',
        'img-3' => 'assets/img/portfolio/tugas2js3.png',
        'a-img' => 'assets/img/portfolio/tugas2js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Daftar Pegawai',
        'portofolio-desc' => 'Ini adalah Tugas 2 Javascript, membuat dokumen html dengan menggunakan perulangan javascript'
    ],
    [
        'id' => 7,
        'title' => 'Tugas 3 Javascript',
        'subtitle' => 'Daftar Pegawai',
        'd-title' => 'Tugas 3 Javascript | Daftar Pegawai',
        'img' => 'assets/img/portfolio/tugas3js1.png',
        'img-2' => 'assets/img/portfolio/tugas3js2.png',
        'img-3' => 'assets/img/portfolio/tugas3js3.png',
        'a-img' => 'assets/img/portfolio/tugas3js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Daftar Pegawai',
        'portofolio-desc' => 'Ini adalah Tugas 3 Javascript, membuat dokumen html dengan menggunakan perulangan javascript'
    ],
    [
        'id' => 8,
        'title' => 'Tugas 4 Javascript',
        'subtitle' => 'Data Form Pembelian',
        'd-title' => 'Tugas 4 Javascript | Data Form Pembelian',
        'img' => 'assets/img/portfolio/tugas4js1.png',
        'img-2' => 'assets/img/portfolio/tugas4js2.png',
        'img-3' => 'assets/img/portfolio/tugas4js3.png',
        'a-img' => 'assets/img/portfolio/tugas4js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Data Form Pembelian',
        'portofolio-desc' => 'Ini adalah Tugas 4 Javascript'
    ],
    [
        'id' => 9,
        'title' => 'Tugas 5 Javascript',
        'subtitle' => 'Data Form Pembelian',
        'd-title' => 'Tugas 5 Javascript | Data Form Pembelian',
        'img' => 'assets/img/portfolio/tugas5js1.png',
        'img-2' => 'assets/img/portfolio/tugas5js2.png',
        'img-3' => 'assets/img/portfolio/tugas5js3.png',
        'a-img' => 'assets/img/portfolio/tugas5js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Data Form Pembelian',
        'portofolio-desc' => 'Ini adalah Tugas 5 Javascript'
    ],
    [
        'id' => 10,
        'title' => 'Tugas 6 Javascript',
        'subtitle' => 'Data Informasi Gempa',
        'd-title' => 'Tugas 6 Javascript | Data Informasi Gempa',
        'img' => 'assets/img/portfolio/tugas6js1.png',
        'img-2' => 'assets/img/portfolio/tugas6js2.png',
        'img-3' => 'assets/img/portfolio/tugas6js3.png',
        'a-img' => 'assets/img/portfolio/tugas6js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Data Informasi Gempa',
        'portofolio-desc' => 'Ini adalah Tugas 6 Javascript'
    ],
    [
        'id' => 11,
        'title' => 'Tugas 7 Javascript',
        'subtitle' => 'Aplikasi Sederhana',
        'd-title' => 'Tugas 7 Javascript |Aplikasi Sederhana',
        'img' => 'assets/img/portfolio/tugas7js1.png',
        'img-2' => 'assets/img/portfolio/tugas7js2.png',
        'img-3' => 'assets/img/portfolio/tugas7js3.png',
        'a-img' => 'assets/img/portfolio/tugas7js1.png',
        'div' => 'filter-js',
        'category' => 'Pemrograman Javascript',
        'client' => 'MSIB3 - PT. Nurul Fikri',
        'project-date' => '12 September 2022',
        'project-url' => 'https://github.com/andik71/msib3-javascript.git',
        'portofolio-title' => 'Aplikasi Sederhana',
        'portofolio-desc' => 'Ini adalah Tugas 7 Javascript'
    ],
];
